In [1]:
import numpy as np
num = np.arange(0,11)
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
# Numpy - Numerical Python
# NumPy arrays are stored at one continuous place in memory unlike lists - locality of reference in computer science.

arr1 = np.array([1, 2, 3]) #  1-D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]]) # 2-D array
arr3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]) # 3-D array

print(arr1,'\n \n 2D - ', arr2, '\n \n 3D - ', arr3)

[1 2 3] 
 
 2D -  [[1 2 3]
 [4 5 6]] 
 
 3D -  [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [8]:
arr4 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr4)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [9]:
print(arr1.ndim, arr2.ndim, arr3.ndim, arr4.ndim) # Ndim - to show dimension of array

1 2 3 3


In [20]:
a = np.arange(1, 10)
print(a)

y = a.astype("b")
print(y)

print(y.dtype)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
int8


In [22]:
import pandas as pd # loc and iloc

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df.loc[2], "\n")
print(df.loc[1])

calories    390
duration     45
Name: 2, dtype: int64 

calories    380
duration     40
Name: 1, dtype: int64


In [ ]:
# [dropna(), inplace] fillna()

In [ ]:

#       Duration          Date  Pulse  Maxpulse  Calories
#   0         60  '2020/12/01'    110       130     409.1
#   1         60  '2020/12/02'    117       145     479.0

import pandas as pd
df = pd.read_csv('data.csv')
# <------------ df['Date'] = pd.to_datetime(df['Date']) --------> 
print(df.to_string())

In [ ]:
df.drop_duplicates(inplace = True)

df.duplicated() # returns true for duplicates